---
# DESCRIPTION
#  This is an ansible playbook that used to replace job credentials for 
#  a list of job templates
# 

- hosts: localhost
  gather_facts: no 
  become: true


  tasks:
  - name: show variables values
    debug:  
      msg: target host of this playbook is {{target}}